version: "3.8"

services:
  db:
    image: mysql
    container_name: testdb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=sopes_db
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - net
  back:
    image: andrecorado/api:v1.0
    container_name: so1_p1_server
    privileged: true
    pid: host
    restart: always
    ports:
      - 8080:8080
    networks:
      - net
    links:
      - db
    volumes:
      - /proc:/host_proc
    depends_on:
      - db
    environment:
      - MYSQL_URI=root:${MYSQL_ROOT_PASSWORD}@tcp(mysql:3306)/monitor?charset=utf8&parseTime=true
  frontend:
    image: andrecorado/front:v0.01
    container_name: so1_p1_client
    restart: always
    ports:
      - 80:80
    depends_on:
      - back
    links:
      - back
    networks:
      - net
volumes:
  db-data:
networks:
  net:
    driver: bridge
